# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b00a4bd92cf50155537977cfabeae2e6d8bc5f5b8b3d852e64498fc0f338ab499caf955db44e95e772d0877d15ef17c9d7c43ac0b37e0d3817b015917f6fef2

test:
  secret_key_base: 121548aa63b15976d80197b3d4f68e90c0f68008dc043038e52e01fe647b86e058f1879bb73462247c110ff994002383be3823498f729c9176349f4edfa93267

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
